version: "3.9"

services:
  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Port trên host là 3307, bên trong container 3306
    volumes:
      - inventory-db-data:/var/lib/mysql

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    restart: always
    depends_on:
      - inventory-db
    environment:
      DB_HOST: inventory-db
      DB_PORT: 3306
      DB_NAME: inventory_db
      DB_USER: user
      DB_PASSWORD: password
      DATABASE_URL: mysql+pymysql://user:password@inventory-db:3306/inventory_db
      PYTHONPATH: /app
    ports:
      - "8001:8000"
      - "50051:50051" # gRPC
    volumes:
      - ./inventory-service:/app
    command: ["./wait-for-it.sh", "inventory-db", "3306", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]


volumes:
  inventory-db-data:
