version: "3.8"

services:
  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - inventory-db-data:/var/lib/mysql

  inventory-service:
    build:
      context: ./inventory-service
    image: truongthuanr/store-management:latest
    container_name: inventory-service
    restart: always
    depends_on:
      - inventory-db
    environment:
      DB_HOST: inventory-db
      DB_PORT: 3306
      DB_NAME: inventory_db
      DB_USER: user
      DB_PASSWORD: password
      DATABASE_URL: mysql+pymysql://user:password@inventory-db:3306/inventory_db
    ports:
      - "8001:8000" # HTTP API
      - "50051:50051" # gRPC
    volumes:
      - ./inventory-service:/app

  product-db:
    image: mysql:8.0
    container_name: product-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql

  product-service:
    build:
      context: ./product-service
    image: truongthuanr/product-service:latest
    container_name: product-service
    restart: always
    depends_on:
      - product-db
      - inventory-service  # để có thể gọi grpc tới inventory
    environment:
      DB_HOST: product-db
      DB_PORT: 3306
      DB_NAME: product_db
      DB_USER: user
      DB_PASSWORD: password
      DATABASE_URL: mysql+pymysql://user:password@product-db:3306/product_db
      INVENTORY_GRPC_HOST: inventory-service
      INVENTORY_GRPC_PORT: 50051
    ports:
      - "8002:8000"
    volumes:
      - ./product-service:/app

volumes:
  inventory-db-data:
  product-db-data:
