# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/proto/inventory.proto\x12\tinventory\"\x07\n\x05\x45mpty\"(\n\x10InventoryRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\x05\"1\n\x1bInventoryRequestByProductId\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"D\n\x16InventoryUpdateRequest\x12\x14\n\x0cinventory_id\x18\x01 \x01(\x05\x12\x14\n\x0cstock_change\x18\x02 \x01(\x05\"m\n\x16\x43reateInventoryRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x98\x01\n\rInventoryItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\r\n\x05stock\x18\x06 \x01(\x05\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\";\n\x11InventoryResponse\x12&\n\x04item\x18\x01 \x01(\x0b\x32\x18.inventory.InventoryItem\"G\n\x1cInventoryResponseByProductId\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x13\n\x0btotal_stock\x18\x02 \x01(\x05\"Z\n\x17UpdateInventoryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12.\n\x0cupdated_item\x18\x02 \x01(\x0b\x32\x18.inventory.InventoryItem\"8\n\rInventoryList\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.inventory.InventoryItem2\xb4\x03\n\x10InventoryService\x12R\n\x0f\x43reateInventory\x12!.inventory.CreateInventoryRequest\x1a\x1c.inventory.InventoryResponse\x12I\n\x0cGetInventory\x12\x1b.inventory.InventoryRequest\x1a\x1c.inventory.InventoryResponse\x12X\n\x0fUpdateInventory\x12!.inventory.InventoryUpdateRequest\x1a\".inventory.UpdateInventoryResponse\x12;\n\rListInventory\x12\x10.inventory.Empty\x1a\x18.inventory.InventoryList\x12j\n\x17GetInventoryByProductId\x12&.inventory.InventoryRequestByProductId\x1a\'.inventory.InventoryResponseByProductIdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=40
  _globals['_EMPTY']._serialized_end=47
  _globals['_INVENTORYREQUEST']._serialized_start=49
  _globals['_INVENTORYREQUEST']._serialized_end=89
  _globals['_INVENTORYREQUESTBYPRODUCTID']._serialized_start=91
  _globals['_INVENTORYREQUESTBYPRODUCTID']._serialized_end=140
  _globals['_INVENTORYUPDATEREQUEST']._serialized_start=142
  _globals['_INVENTORYUPDATEREQUEST']._serialized_end=210
  _globals['_CREATEINVENTORYREQUEST']._serialized_start=212
  _globals['_CREATEINVENTORYREQUEST']._serialized_end=321
  _globals['_INVENTORYITEM']._serialized_start=324
  _globals['_INVENTORYITEM']._serialized_end=476
  _globals['_INVENTORYRESPONSE']._serialized_start=478
  _globals['_INVENTORYRESPONSE']._serialized_end=537
  _globals['_INVENTORYRESPONSEBYPRODUCTID']._serialized_start=539
  _globals['_INVENTORYRESPONSEBYPRODUCTID']._serialized_end=610
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_start=612
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_end=702
  _globals['_INVENTORYLIST']._serialized_start=704
  _globals['_INVENTORYLIST']._serialized_end=760
  _globals['_INVENTORYSERVICE']._serialized_start=763
  _globals['_INVENTORYSERVICE']._serialized_end=1199
# @@protoc_insertion_point(module_scope)
