# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\x07\n\x05\x45mpty\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"@\n\x14ProductUpdateRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x14\n\x0cstock_change\x18\x02 \x01(\x05\"~\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"6\n\x0fProductResponse\x12#\n\x07product\x18\x01 \x01(\x0b\x32\x12.inventory.Product\"W\n\x17UpdateInventoryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12+\n\x0fupdated_product\x18\x02 \x01(\x0b\x32\x12.inventory.Product\"5\n\rInventoryList\x12$\n\x08products\x18\x01 \x03(\x0b\x32\x12.inventory.Product2\xee\x01\n\x10InventoryService\x12\x45\n\x0cGetInventory\x12\x19.inventory.ProductRequest\x1a\x1a.inventory.ProductResponse\x12V\n\x0fUpdateInventory\x12\x1f.inventory.ProductUpdateRequest\x1a\".inventory.UpdateInventoryResponse\x12;\n\rListInventory\x12\x10.inventory.Empty\x1a\x18.inventory.InventoryListB\rZ\x0binventorypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013inventorypb'
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_PRODUCTREQUEST']._serialized_start=39
  _globals['_PRODUCTREQUEST']._serialized_end=75
  _globals['_PRODUCTUPDATEREQUEST']._serialized_start=77
  _globals['_PRODUCTUPDATEREQUEST']._serialized_end=141
  _globals['_PRODUCT']._serialized_start=143
  _globals['_PRODUCT']._serialized_end=269
  _globals['_PRODUCTRESPONSE']._serialized_start=271
  _globals['_PRODUCTRESPONSE']._serialized_end=325
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_start=327
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_end=414
  _globals['_INVENTORYLIST']._serialized_start=416
  _globals['_INVENTORYLIST']._serialized_end=469
  _globals['_INVENTORYSERVICE']._serialized_start=472
  _globals['_INVENTORYSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
