# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\"\n\x0cStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\"A\n\rStockResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x03\"7\n\x12UpdateStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x05\x32\x99\x01\n\x10InventoryService\x12=\n\x08GetStock\x12\x17.inventory.StockRequest\x1a\x18.inventory.StockResponse\x12\x46\n\x0bUpdateStock\x12\x1d.inventory.UpdateStockRequest\x1a\x18.inventory.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=30
  _globals['_STOCKREQUEST']._serialized_end=64
  _globals['_STOCKRESPONSE']._serialized_start=66
  _globals['_STOCKRESPONSE']._serialized_end=131
  _globals['_UPDATESTOCKREQUEST']._serialized_start=133
  _globals['_UPDATESTOCKREQUEST']._serialized_end=188
  _globals['_INVENTORYSERVICE']._serialized_start=191
  _globals['_INVENTORYSERVICE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
