# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """==========================
    Service Definitions
    ==========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventory = channel.unary_unary(
                '/inventory.InventoryService/GetInventory',
                request_serializer=inventory__pb2.ProductRequest.SerializeToString,
                response_deserializer=inventory__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateInventory = channel.unary_unary(
                '/inventory.InventoryService/UpdateInventory',
                request_serializer=inventory__pb2.ProductUpdateRequest.SerializeToString,
                response_deserializer=inventory__pb2.UpdateInventoryResponse.FromString,
                _registered_method=True)
        self.ListInventory = channel.unary_unary(
                '/inventory.InventoryService/ListInventory',
                request_serializer=inventory__pb2.Empty.SerializeToString,
                response_deserializer=inventory__pb2.InventoryList.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """==========================
    Service Definitions
    ==========================

    """

    def GetInventory(self, request, context):
        """Lấy thông tin inventory của một sản phẩm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInventory(self, request, context):
        """Cập nhật số lượng tồn kho (tăng/giảm)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInventory(self, request, context):
        """Lấy danh sách toàn bộ sản phẩm trong kho
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventory,
                    request_deserializer=inventory__pb2.ProductRequest.FromString,
                    response_serializer=inventory__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInventory,
                    request_deserializer=inventory__pb2.ProductUpdateRequest.FromString,
                    response_serializer=inventory__pb2.UpdateInventoryResponse.SerializeToString,
            ),
            'ListInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInventory,
                    request_deserializer=inventory__pb2.Empty.FromString,
                    response_serializer=inventory__pb2.InventoryList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """==========================
    Service Definitions
    ==========================

    """

    @staticmethod
    def GetInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetInventory',
            inventory__pb2.ProductRequest.SerializeToString,
            inventory__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/UpdateInventory',
            inventory__pb2.ProductUpdateRequest.SerializeToString,
            inventory__pb2.UpdateInventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ListInventory',
            inventory__pb2.Empty.SerializeToString,
            inventory__pb2.InventoryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
